# Generated by Django 5.0.5 on 2024-05-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('stock_min', models.IntegerField()),
                ('stock_max', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
